from __future__ import annotations

import argparse
from pathlib import Path
from typing import List

from PIL import Image, ImageDraw, ImageFont


DEFAULT_FONT_PATH = Path(r"C:\Windows\Fonts\simhei.ttf")
DEFAULT_TEXT_PATH = Path("Middlewares/LVGL/Font/checkout_ui_font_texts.txt")
DEFAULT_OUTPUT_C = Path("Middlewares/LVGL/Font/Font20.c")
DEFAULT_OUTPUT_H = Path("Middlewares/LVGL/Font/Font20.h")
DEFAULT_SYMBOL = "Font20"
DEFAULT_MACRO = "FONT20"
DEFAULT_SIZE = 20


def unique_chars_from_text(path: Path) -> List[str]:
    seen = set()
    chars: List[str] = []
    text = path.read_text(encoding="utf-8")
    for ch in text:
        if ch in "\r\n":
            continue
        if ch not in seen:
            seen.add(ch)
            chars.append(ch)
    return chars


def format_hex_bytes(data: List[int], per_line: int = 12) -> str:
    if not data:
        return "    0x00"

    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{value:02X}" for value in chunk) + ",")
    return "\n".join(lines)


def format_uint16(data: List[int], per_line: int = 8) -> str:
    if not data:
        return "    0x0000"

    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i : i + per_line]
        lines.append("    " + ", ".join(f"0x{value:04X}" for value in chunk) + ",")
    return "\n".join(lines)


def pack_4bpp(image: Image.Image) -> List[int]:
    width, height = image.size
    pixels = image.load()
    packed: List[int] = []

    for y in range(height):
        x = 0
        while x < width:
            left = pixels[x, y]
            left_nibble = min(15, (left + 8) // 17)

            if x + 1 < width:
                right = pixels[x + 1, y]
                right_nibble = min(15, (right + 8) // 17)
            else:
                right_nibble = 0

            packed.append((left_nibble << 4) | right_nibble)
            x += 2

    return packed


def render_glyph(font: ImageFont.FreeTypeFont, ch: str) -> dict:
    x0, y0, x1, y1 = font.getbbox(ch)
    box_w = x1 - x0
    box_h = y1 - y0
    adv_w = int(round(font.getlength(ch) * 16))

    bitmap: List[int] = []
    if box_w > 0 and box_h > 0:
        image = Image.new("L", (box_w, box_h), 0)
        draw = ImageDraw.Draw(image)
        draw.text((-x0, -y0), ch, font=font, fill=255)
        bitmap = pack_4bpp(image)

    return {
        "char": ch,
        "codepoint": ord(ch),
        "adv_w": adv_w,
        "box_w": box_w,
        "box_h": box_h,
        "ofs_x": x0,
        "ofs_y": y0,
        "bbox_bottom": y1,
        "bitmap": bitmap,
    }


def generate_font_source(
    chars: List[str],
    font_path: Path,
    size: int,
    symbol: str,
    macro_name: str,
    source_text_path: Path,
) -> str:
    font = ImageFont.truetype(str(font_path), size)
    glyphs = [render_glyph(font, ch) for ch in sorted(chars, key=ord)]
    _, descent = font.getmetrics()
    line_height = size
    base_line = descent

    bitmap_bytes: List[int] = []
    glyph_dsc_lines = [
        "    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,"
    ]

    bitmap_sections = []
    bitmap_index = 0
    for glyph in glyphs:
        glyph["ofs_y"] = (line_height - base_line + 1) - glyph["bbox_bottom"]
        bitmap_sections.append(f"    /* U+{glyph['codepoint']:04X} */")
        if glyph["bitmap"]:
            bitmap_sections.append(format_hex_bytes(glyph["bitmap"]))
            bitmap_sections.append("")
        glyph_dsc_lines.append(
            "    "
            + "{.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = %d, .ofs_y = %d},"
            % (
                bitmap_index,
                glyph["adv_w"],
                glyph["box_w"],
                glyph["box_h"],
                glyph["ofs_x"],
                glyph["ofs_y"],
            )
        )
        bitmap_bytes.extend(glyph["bitmap"])
        bitmap_index += len(glyph["bitmap"])

    if bitmap_sections and bitmap_sections[-1] == "":
        bitmap_sections.pop()

    codepoints = [glyph["codepoint"] for glyph in glyphs]
    range_start = min(codepoints)
    range_length = max(codepoints) - range_start + 1
    unicode_list = [codepoint - range_start for codepoint in codepoints]

    return f"""/*******************************************************************************
 * Auto-generated by tools/generate_checkout_ui_font.py
 * Source font: {font_path}
 * Font size: {size}px
 * Charset source: {source_text_path.as_posix()}
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef {macro_name}
#define {macro_name} 1
#endif

#if {macro_name}

/*-----------------
 *    BITMAPS
 *----------------*/

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(bitmap_sections)}
}};

/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{chr(10).join(glyph_dsc_lines)}
}};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_0[] = {{
{format_uint16(unicode_list)}
}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = {range_start}, .range_length = {range_length}, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = {len(unicode_list)}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }}
}};

/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LV_VERSION_CHECK(8, 0, 0)
static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {{
#else
static lv_font_fmt_txt_dsc_t font_dsc = {{
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
#if LV_VERSION_CHECK(8, 0, 0)
    .cache = &cache
#endif
}};

/*-----------------
 *  PUBLIC FONT
 *----------------*/

#if LV_VERSION_CHECK(8, 0, 0)
const lv_font_t {symbol} = {{
#else
lv_font_t {symbol} = {{
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {line_height},
    .base_line = {base_line},
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -1,
    .underline_thickness = 1,
#endif
    .dsc = &font_dsc
}};

#endif /* {macro_name} */
"""


def generate_header(symbol: str) -> str:
    return f"""#pragma once

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

LV_FONT_DECLARE({symbol});
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate an LVGL font source file for the checkout UI.")
    parser.add_argument("--font", type=Path, default=DEFAULT_FONT_PATH)
    parser.add_argument("--text", type=Path, default=DEFAULT_TEXT_PATH)
    parser.add_argument("--output-c", type=Path, default=DEFAULT_OUTPUT_C)
    parser.add_argument("--output-h", type=Path, default=DEFAULT_OUTPUT_H)
    parser.add_argument("--symbol", default=DEFAULT_SYMBOL)
    parser.add_argument("--macro", default=DEFAULT_MACRO)
    parser.add_argument("--size", type=int, default=DEFAULT_SIZE)
    args = parser.parse_args()

    chars = unique_chars_from_text(args.text)
    source = generate_font_source(chars, args.font, args.size, args.symbol, args.macro, args.text)
    header = generate_header(args.symbol)

    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_h.parent.mkdir(parents=True, exist_ok=True)
    args.output_c.write_text(source, encoding="utf-8")
    args.output_h.write_text(header, encoding="utf-8")

    print(f"Generated {args.output_c}")
    print(f"Generated {args.output_h}")
    print(f"Unique chars: {len(chars)}")


if __name__ == "__main__":
    main()
